# wrangler.toml - Konfiguration für Cloudflare Pages
name = "laufplanerpro"
compatibility_date = "2023-09-04"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "build"

# Konfiguration der Cloudflare D1 Datenbank
[[d1_databases]]
binding = "DB"
database_name = "training_plans_db"
database_id = "30ca8fe2-fb17-4cfa-963e-a3eeda8cb5c5"

# Preview environment
[env.preview]
vars = { NODE_ENV = "preview" }
[[env.preview.d1_databases]]
binding = "DB"
database_name = "training_plans_db"
database_id = "30ca8fe2-fb17-4cfa-963e-a3eeda8cb5c5"

# Production environment
[env.production]  
vars = { NODE_ENV = "production" }
[[env.production.d1_databases]]
binding = "DB"
database_name = "training_plans_db"
database_id = "30ca8fe2-fb17-4cfa-963e-a3eeda8cb5c5"
# API Keys (werden in Cloudflare Dashboard als Secrets gesetzt)
# STRAVA_CLIENT_ID = "your_strava_client_id"
# STRAVA_CLIENT_SECRET = "your_strava_client_secret"
# GARMIN_CONSUMER_KEY = "your_garmin_key"
# GARMIN_CONSUMER_SECRET = "your_garmin_secret"
# POLAR_CLIENT_ID = "your_polar_client_id"
# POLAR_CLIENT_SECRET = "your_polar_client_secret"
# WAHOO_CLIENT_ID = "your_wahoo_client_id"
# WAHOO_CLIENT_SECRET = "your_wahoo_client_secret"
# JWT_SECRET = "your_jwt_secret_key"
